- mtbf_driver/MtbfTestCase.py
- mtbf_driver/tests/mtbf/camera/test_mtbf_camera_capture_video.py
- mtbf_driver/tests/mtbf/camera/test_mtbf_camera_multiple_shots.py
- mtbf_driver/tests/mtbf/keyboard/test_mtbf_keyboard_predictive_key.py
- mtbf_driver/tests/mtbf/music/test_mtbf_music_song_3gp.py
1. Turn on screen in cleanup_gaia
2. Slight modification for v2.2
> Turn on screen at the begin of tests

- .gitignore
- mtbf_driver/mtbf.py
- mtbf_driver/utils/memory_report_args.py
memory report (using get_about_memory)
> Repair memory report

- mtbf_driver/mtbf_apps/camera/__init__.py
- mtbf_driver/mtbf_apps/camera/app.py
- mtbf_driver/mtbf_apps/music/app.py
- mtbf_driver/mtbf_apps/music/regions/list_view.py
- mtbf_driver/tests/mtbf/browser/test_mtbf_browser_navigation.py
- mtbf_driver/tests/mtbf/camera/test_mtbf_camera_capture_video.py
- mtbf_driver/tests/mtbf/camera/test_mtbf_camera_multiple_shots.py
- mtbf_driver/tests/mtbf/music/test_mtbf_music_song_3gp.py
change list--
add camera apps, add sleep after press to fix the tap switch issue
add music app.py to fix the scroll checking
modify test case broswer navigation, camera, music
please help to review, @ypwalter r?
> Fix MBTF issues for 2.2

- mtbf_driver/mtbf.py
It's a simple fix. @zapion @ShakoHo, if there is no further concern, I will merge.
> adding current mtbf time every run

- makefile
add a makefile to help dummy user
@zapion , @ypwalter  r?
> add new makefile to help dummy user

- mtbf_driver/tests/test_dummy_case.py
Depend on bug in gaia ui test, will update bug id latter
> increase idle time by 120 seconds. Turn off screen while idled

- mtbf_driver/tests/test_dummy_case.py
@ShakoHo , could you please review this update?
> update sleep time to 30s at dummy case

- mtbf_driver/runlist/flame_v220.list
- mtbf_driver/runlist/nexus5_v220.list
- mtbf_driver/runlist/temp_disable.list
remove temp disable test case due to Bug 1096385
@ypwalter r?
> remove temp disable test case

- mtbf_driver/mtbf.py
add DMError exception handling outside of the run_tests
> add DMError exception handling for run_tests

- requirements.txt
@zapion @ShakoHo, an easy patch. r?
> adding dependency for v2.2

- mtbf_driver/mtbf.py
To address B2G info threads issue. 
Also, bring back Shako's changes on cleanup gaia in dummy test.
> B2G info nothread

- mtbf_driver/mtbf.py
another pull request for trial run on Nexus 5
@ypwalter  r?
> Override gaiatestrunner class

- mtbf_driver/conf/nexus5_v220_nocamera.json
- mtbf_driver/mtbf.py
- mtbf_driver/runlist/nexus5_v220_nocamera.list
> Modify step get to given full path of tests

- mtbf_driver/mtbf.py
couple lines modification for rootdir..
> modify the rootdir to abs full path

- mtbf_driver/mtbf.py
- mtbf_driver/tests/test_dummy_case.py
> add-wait-for-device-after-adb

- mtbf_driver/mtbf.py
minor fix to make sure if rootdir value set to abspath....Thanks Paul!!
> fix the condition if rootdir conf value is set to abspath

- mtbf_driver/mtbf.py
> Fix memory leak

- mtbf_driver/mtbf.py
Another workaround for memory leak issue
> fixing for memory leak: gaia_result_modifiers

- mtbf_driver/mtbf.py
> merge-paul-fix

- mtbf_driver/mtbf.py
Fix for "please start a session"
> remove marionette re-use

- mtbf_driver/tests/test_dummy_case.py
comment out setvolume(0) in dummytestcase
> modify-clean-up-gaia

- mtbf_driver/mtbf_apps/music/app.py
> fix-music-test-case

- mtbf_driver/mtbf_apps/camera/app.py
- mtbf_driver/tests/mtbf/camera/test_mtbf_camera_multiple_shots.py
- add mtbf camera app object 
- add a method to kill abnormal status camera app in mtbf camera app
@zapion , @ypwalter  r?
> add-kill-abnormalstatus-camera-app

- mtbf_driver/mtbf.py
TODO: mtbf operation uses argparse so we need conversion.  That part can be taken if all stacks use argparse.
> upgrade argparse

- mtbf_driver/mtbf.py
Reverts Mozilla-TWQA/MTBF-Driver#104
> Revert "upgrade argparse"

- mtbf_driver/mtbf_apps/settings/app.py
- mtbf_driver/tests/mtbf/settings/test_mtbf_settings_bt.py
- mtbf_driver/tests/mtbf/settings/test_mtbf_settings_wifi.py
due to the gaia app architecture change, I can't give a patch for the current app of bluetooth, so I will implement the bluetooth control method in mtbf app
> Fix settings test case

- mtbf_driver/tests/mtbf/browser/test_mtbf_browser_cell_data.py
- mtbf_driver/tests/mtbf/browser/test_mtbf_browser_clear_browsing_history.py
- mtbf_driver/tests/mtbf/browser/test_mtbf_browser_search.py
fix browser test case
have dependency with Bug 1203060, Bug 1205523
> fix-browser-test-cases

- mtbf_driver/tests/mtbf/keyboard/test_mtbf_keyboard.py
modify the test case to able run it on aries... have dependency with bug 1205238
> fix-keyboard-test-case

- mtbf_driver/mtbf.py
Change runinfo start time format for jenkins job
> runinfo using jenkins timestamp
